version: '3.8'
services:
  postgres:
    image: postgres
    restart: always 
    ports:
      - '5432:5432'
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on: 
      - postgres
  